// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gestao_sinistros_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Apolice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<int>("RamoSeguro")
                        .HasColumnType("integer")
                        .HasColumnName("ramo_seguro");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_apolices");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_apolices_cliente_id");

                    b.ToTable("apolices", (string)null);
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.HistoricoSinistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("SinistroId")
                        .HasColumnType("uuid")
                        .HasColumnName("sinistro_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_historico_sinistros");

                    b.HasIndex("SinistroId")
                        .HasDatabaseName("ix_historico_sinistros_sinistro_id");

                    b.ToTable("historico_sinistros", (string)null);
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Sinistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApoliceId")
                        .HasColumnType("uuid")
                        .HasColumnName("apolice_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ocorrencia");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("MotivoNegacao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_negacao");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorAprovado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_aprovado");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_estimado");

                    b.HasKey("Id")
                        .HasName("pk_sinistros");

                    b.HasIndex("ApoliceId")
                        .HasDatabaseName("ix_sinistros_apolice_id");

                    b.ToTable("sinistros", (string)null);
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Apolice", b =>
                {
                    b.HasOne("gestao_sinistros_api.Application.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Apolices")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_apolices_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.HistoricoSinistro", b =>
                {
                    b.HasOne("gestao_sinistros_api.Application.Domain.Entities.Sinistro", "Sinistro")
                        .WithMany("Historicos")
                        .HasForeignKey("SinistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_sinistros_sinistros_sinistro_id");

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Sinistro", b =>
                {
                    b.HasOne("gestao_sinistros_api.Application.Domain.Entities.Apolice", "Apolice")
                        .WithMany("Sinistros")
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sinistros_apolices_apolice_id");

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Apolice", b =>
                {
                    b.Navigation("Sinistros");
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Apolices");
                });

            modelBuilder.Entity("gestao_sinistros_api.Application.Domain.Entities.Sinistro", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
